# **Basic Linear Algebra with Numpy**

In [ ]:
import numpy as np

##Phép cộng và trừ ma trận

In [ ]:
#Phép cộng và trừ ma trận

A=np.array([[1,2], [3,4]])
B=np.array([[5,6], [7,8]])
C=A+B
D=A-B
print(f"{C} \n")
print(D)

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]]


##Tính tổng và hiệu

In [ ]:
#Tính tổng và hiệu
c=np.array([[2,-3],[4,-5]])
d=np.array([[1,4],[-2,6]])
print(f"{c+d} \n")
print(c-d)

[[3 1]
 [2 1]] 

[[  1  -7]
 [  6 -11]]


###Phép nhân Hadamard hai ma trận

In [ ]:
#Phép nhân HAdamard hai ma trận

a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
c=a*b
print(c)

[[ 5 12]
 [21 32]]


In [ ]:
e=np.array([[0,1,2],[3,4,5]])
f=np.array([[5,4,3],[2,1,0]])
print(e*f)

[[0 4 6]
 [6 4 0]]


##Tích vô hướng

In [ ]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print("Tích vô hường hai vector:", np.dot(v1,v2))


Tích vô hường hai vector: 32


In [ ]:
import numpy as np
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1.dot(v2))

32


##Tích chập (Convolution)

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
k=np.array([[1,0],[0,-1]])

def matrix_convolution(a,k):
    n,m=a.shape
    p,q=k.shape
    result_shape=(n-p+1,m-q+1)
    result=np.zeros(result_shape)
    for i in range(n-p+1):
        for j in range(m-q+1):
            result[i,j]=np.sum(a[i:i+p,j:j+q]*k)
    return result

In [ ]:
result=matrix_convolution(a,k)
print(result)

[[-4. -4.]
 [-4. -4.]]


In [ ]:
import numpy as np
a=np.array([[1,2,0,1],[0,4,1,6],[7,8,9,0]])
k=np.array([[1,0],[0,-1]])

def matrix_convolution(a,k):
    n,m=a.shape
    p,q=k.shape
    result_shape=(n-p+1,m-q+1)  # print(result_shape)= (2,3)
    result=np.zeros(result_shape)  #  print(result)= [[0. 0. 0.], [0. 0. 0.]]
    for i in range(n-p+1):
        for j in range(m-q+1):
            result[i,j]=np.sum(a[i:i+p,j:j+q]*k)
    return result

In [ ]:
result=matrix_convolution(a,k)
print(result)

[[-3.  1. -6.]
 [-8. -5.  1.]]


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
a=np.array([[1,2],[4,5]])
k=np.array([[1,0],[0,-1]])
z=a*k
np.sum(z)

-4

In [ ]:
np.zeros(3*2)

array([0., 0., 0., 0., 0., 0.])

## Xoay vector một góc theta (degree/rad)

#### numpy hỗ trợ tự động broadcasting. Tuy nhiên nếu thực hiện các phép toán phức tạp hoặc không rõ ràng về cách các mảng được phát sóng, bạn có thể cần phải sử dụng reshape để đảm bảo kích thước các mảng tương thích với nhau

In [ ]:
import numpy as np
v=np.array([1,0])
theta=-45
theta_rad=np.radians(theta)
rotation_matrix=np.array([
    [np.cos(theta_rad), -np.sin(theta_rad)],
    [np.sin(theta_rad), np.cos(theta_rad)]
])
v_new=np.dot(rotation_matrix,v)
print(v_new)

[ 0.70710678 -0.70710678]


In [ ]:
import numpy as np
def rotate_vector(vector, degree):
    rad=np.radians(degree)
    rotation_matrix=np.array([
    [np.cos(rad), -np.sin(rad)],
    [np.sin(rad), np.cos(rad)]
])
    return np.dot(rotation_matrix,vector)

In [ ]:
vector= np.array([1,0])
degree=45
print(rotate_vector(vector, degree))

[0.70710678 0.70710678]


In [ ]:
import numpy as np
v=np.array([1,0])
r=np.array([[np.cos(np.radians(45)),-np.sin(np.radians(45))], [np.sin(np.radians(45)), np.cos(np.radians(45))]])
print(r.dot(v))

[0.70710678 0.70710678]


In [ ]:
import numpy as np
v=np.array([1,0])
r=np.array([[np.cos(np.radians(45)),-np.sin(np.radians(45))], [np.sin(np.radians(45)), np.cos(np.radians(45))]])
print(v.dot(r))

[ 0.70710678 -0.70710678]


In [ ]:
import numpy as np

vector = [1, 2, 3]
np.array(vector).shape

(3,)

In [ ]:
theta=45
theta_rad = np.pi/180*45
print(theta_rad)

0.7853981633974483


In [ ]:
pip install numpy

In [ ]:
import numpy as np
zero_matrix=np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_matrix=np.ones((2,2))
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


In [ ]:
rand_matrix=np.random.rand(3,3)
print(rand_matrix)

[[0.6830931  0.75186439 0.345326  ]
 [0.05485909 0.30731292 0.51981654]
 [0.22071823 0.2180787  0.56429845]]


In [ ]:
import numpy as np
identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
A = np. array ([[1 , 2], [3, 4]])

In [ ]:
det_A=np.linalg.det(A)
print(det_A)

-2.0000000000000004


In [ ]:
A_inv=np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
c=A*A_inv
print(c)

[[-2.   2. ]
 [ 4.5 -2. ]]


In [ ]:
i=np.dot(A,A_inv)
print(i)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
b = np.array([[4, 7], [2, 6]])
d=np.linalg.inv(b)
print(d)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
print(np.dot(b,d))

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
rank_A=np.linalg.matrix_rank(A)
print(rank_A)

2


In [ ]:
import numpy as np
A = np.array([[1, 2],[3, 4]])
B=np.array([[0,2],[1,1]])
x=np.linalg.solve(A,B)
print(x)

[[ 1.  -3. ]
 [-0.5  2.5]]


In [ ]:
np.linalg.eig(A)


EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [ ]:
s=[9.52551809, 0.51428572]
np.diag(s)

array([[9.52551809, 0.        ],
       [0.        , 0.51428572]])