# **Numpy - Gram Matrix in Style transfer**

In [ ]:
#Cài đặt Gram Matrix bằng Numpy
import numpy as np
def compute_gram_matrix(feature_map: np.ndarray)-> np.ndarray:
    """
    Tính Gram Matrix từ feature map.
    Args:
        feature_map (np.ndarray): Ma trận đặc trưng có kích thước (C,H,W).
    Returns:
        np.ndarray: Gram Matrix có kích thước (C,C).
    """

    C,H,W= feature_map.shape
    F=feature_map.reshape(C, H*W)
    G=np.dot(F, F.T)
    G/=(H*W)
    return G


In [ ]:
#Test case
np.random.seed(42)
feature_map=np.random.rand(3,4,4)
gram_matrix= compute_gram_matrix(feature_map)
print("Gram Matrix:\n", gram_matrix)

Gram Matrix:
 [[0.33432857 0.2207897  0.27598961]
 [0.2207897  0.19580158 0.19452994]
 [0.27598961 0.19452994 0.32603015]]


## So sánh với Pytorch

In [ ]:
import torch
feature_map_torch=torch.tensor(feature_map, dtype=torch.float32)
F_torch=feature_map_torch.view(3,-1)
gram_matrix_torch= torch.mm(F_torch, F_torch.t())/(4*4)
print("\n Gram Matrix Pytorch: \n", gram_matrix_torch.numpy())


 Gram Matrix Pytorch: 
 [[0.33432856 0.2207897  0.2759896 ]
 [0.2207897  0.19580159 0.19452995]
 [0.2759896  0.19452995 0.32603014]]


# **Bài tập 1**
Tính Gram Matrix từ Feature Map

In [ ]:
import numpy as np
def compute_gram_matrix(feature_map):
    C,H,W=feature_map.shape
    F=feature_map.reshape(C,H*W)    #  F=feature_map.reshape(C,H*W). astype(np.float64)
    G=np.dot(F,F.T)   #G=np.matmul(F, F.T)
    G=G.astype(np.float64)
    G/=(H*W)
    return G


In [ ]:
feature_map=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

gram_matrix=compute_gram_matrix(feature_map)
print(gram_matrix)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]


# **Bài tập 2**
Đo độ tương đồng giữa hai ảnh bằng Gram Matrix

In [ ]:
import numpy as np
def compute_similarity(gram1, gram2):  #np.ndarray-> float
    similarity=np.sum(gram1*gram2)/np.sqrt(np.sum(gram1**2)*np.sum(gram2**2))
    return similarity


In [ ]:
#test case
feature_map1=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

feature_map2=np.array([
    [[2,4],[6,8]],
    [[1,3],[5,7]],
    [[0,2],[4,6]]
])

gram1=compute_gram_matrix(feature_map1)
gram2=compute_gram_matrix(feature_map2)

similarity=compute_similarity(gram1, gram2)
print(similarity)

0.6741245785155123
